### ISSUE TITLE
import error on Mavericks: no suitable image found for _jpype.so.  

### ISSUE THREAD

**Issue by yakazimir** [jpype-project/jpype#91]
Hello, 

I am trying to get jpype 0.5.4.5 working on Mac osx 10.9 (mavericks) with Java JDK 1.6 and python 2.7.5. The setup with python seems to work fine without any compilation errors. However, I get the following error when trying to use the module in python: 
## In [1]: import jpype

ImportError                               Traceback (most recent call last)
<ipython-input-1-e9978938630b> in <module>()
----> 1 import jpype

/Library/Python/2.7/site-packages/jpype/**init**.py in <module>()
     15 #
     16 #*****************************************************************************
---> 17 from _jpackage import *
     18 from _jclass import *
     19 from _jarray import *

/Library/Python/2.7/site-packages/jpype/_jpackage.py in <module>()
     16 #*****************************************************************************
     17 
---> 18 import _jpype
     19 import _jclass
     20 

ImportError: dlopen(/Library/Python/2.7/site-packages/_jpype.so, 2): no suitable image found.  Did find:
    /Library/Python/2.7/site-packages/_jpype.so: mach-o, but wrong architecture

I'm not actually sure how the architecture is getting messed up. Any ideas?

**Comment by puneetjindal** [comment]
Following steps helped me resolve this problem on Mac OS Yosemite
https://github.com/originell/jpype/issues/160
