### ISSUE TITLE
Cannot install under Python 3.10

### ISSUE THREAD

**Issue by cowwoc** [jpype-project/jpype#1009]
When attempting to `pip install JPype1` under Windows 10 I get:

```
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32=1 -Inative\common\include -Inative\python\include -Inative\embedded\include -IC:\Program Files\Java\jdk-17\include -IC:\Program Files\Java\jdk-17\include\win32 -Ic:\users\gili\documents\daikin-one\python\include -IC:\Python310\include -IC:\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tpnative\common\jp_array.cpp /Fobuild\temp.win-amd64-3.10\Release\native\common\jp_array.obj /Zi /EHsc /std:c++14
    jp_array.cpp
C:\Users\Gili\AppData\Local\Temp\pip-install-0fjlkma0\jpype1_aff26bff63844fe7b53cb4f7c7e8c054\native\python\include\jp_pythontypes.h(284): error C2061: syntax error: identifier 'ssize_t'
  C:\Users\Gili\AppData\Local\Temp\pip-install-0fjlkma0\jpype1_aff26bff63844fe7b53cb4f7c7e8c054\native\python\include\jp_pythontypes.h(285): error C2805: binary 'operator [' has too few parameters
  C:\Users\Gili\AppData\Local\Temp\pip-install-0fjlkma0\jpype1_aff26bff63844fe7b53cb4f7c7e8c054\native\python\include\jp_pythontypes.h(285): error C2333: 'JPPyObjectVector::operator []': error in function declaration; skipping function body
  C:\Users\Gili\AppData\Local\Temp\pip-install-0fjlkma0\jpype1_aff26bff63844fe7b53cb4f7c7e8c054\native\common\include\jp_primitivetype.h(44): error C3646: 'getItemSize': unknown override specifier
  C:\Users\Gili\AppData\Local\Temp\pip-install-0fjlkma0\jpype1_aff26bff63844fe7b53cb4f7c7e8c054\native\common\include\jp_primitivetype.h(44): error C2059: syntax error: ')'
  C:\Users\Gili\AppData\Local\Temp\pip-install-0fjlkma0\jpype1_aff26bff63844fe7b53cb4f7c7e8c054\native\common\include\jp_primitivetype.h(44): error C2238: unexpected token(s) preceding ';'
  native\common\jp_array.cpp(181): error C2065: 'ssize_t': undeclared identifier
  native\common\jp_array.cpp(181): error C2146: syntax error: missing ';' before identifier 'itemsize'
  native\common\jp_array.cpp(181): error C2065: 'itemsize': undeclared identifier
  native\common\jp_array.cpp(182): error C2065: 'ssize_t': undeclared identifier
  native\common\jp_array.cpp(182): error C2146: syntax error: missing ';' before identifier 'sz'
  native\common\jp_array.cpp(182): error C2065: 'sz': undeclared identifier
  native\common\jp_array.cpp(188): error C2065: 'itemsize': undeclared identifier
  native\common\jp_array.cpp(188): error C2039: 'getItemSize': is not a member of 'JPPrimitiveType'
  C:\Users\Gili\AppData\Local\Temp\pip-install-0fjlkma0\jpype1_aff26bff63844fe7b53cb4f7c7e8c054\native\common\include\jp_primitivetype.h(20): note: see declaration of 'JPPrimitiveType'
  native\common\jp_array.cpp(189): error C2065: 'sz': undeclared identifier
  native\common\jp_array.cpp(189): error C2065: 'itemsize': undeclared identifier
  native\common\jp_array.cpp(193): error C2065: 'sz': undeclared identifier
  native\common\jp_array.cpp(197): error C2065: 'itemsize': undeclared identifier
  native\common\jp_array.cpp(206): error C2065: 'sz': undeclared identifier
  native\common\jp_array.cpp(216): error C2065: 'itemsize': undeclared identifier
  native\common\jp_array.cpp(224): error C2065: 'itemsize': undeclared identifier
  native\common\jp_array.cpp(227): error C2065: 'sz': undeclared identifier
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

Python 3.9 used to work just fine.

**Comment by John-Hennig** [comment]
I've also noticed that, see [GitHub Actions run on my fork](https://github.com/John-Hennig/jpype/actions/runs/1309517663). Builds on Linux and macOS are fine. Only builds on Windows 10 with Python 3.10 produce these strange syntax errors. Same with the `py3.10` branch.

**Comment by john-hen** [comment]
You missed a spot.

https://github.com/jpype-project/jpype/blob/9c210eb55e508a41114099bf3ebcda873ca71eb9/native/python/include/jp_pythontypes.h#L284

But then it builds with Python 3.10 on Windows.

**Comment by mcrysler** [comment]
Still getting this issue in Windows 11, Python 3.10 while trying to install JayDeBeApi. Output attached.
[pip-errors.txt](https://github.com/jpype-project/jpype/files/8673805/pip-errors.txt)

**Comment by marscher** [comment]
It seems ssize_t is not known in MSVC (e.g. https://github.com/vlm/asn1c/issues/159)

**Comment by marscher** [comment]
So I guess we would need a custom definition for it, in case jpype is built by MSVC @Thrameos

**Comment by marscher** [comment]
Sorry, I should have read the whole thread. We have replaced ssize_t with Py_ssize_t a long time ago. Is Jaydebe using an outdated version of JPype?

**Comment by john-hen** [comment]
The latest release, JPype 1.3.0, does not contain the fix discussed here, @marscher.

**Comment by marscher** [comment]
Right, but is fixed on master, so we need another release to get Python-3.10 working.

**Comment by rethat** [comment]
> Still getting this issue in Windows 11, Python 3.10 while trying to install JayDeBeApi. Output attached. [pip-errors.txt](https://github.com/jpype-project/jpype/files/8673805/pip-errors.txt)

I have the same your issue, and I solved it by steps:
1. go to this link https://www.lfd.uci.edu/~gohlke/pythonlibs/#JPype and download the wheel
ex: JPype1‑1.3.0‑cp310‑cp310‑win_amd64.whl
2. using pip to install package just downloaded
`pip install --find-links C:\Temp\ Jpype1`
with C:\Temp is a folder contents your package
3. install JayDeBeApi 
`pip install JayDeBeApi`

Hope this help
